import type {
  ChatMessage,
  Community,
  Conversation,
  Gift,
  NearbyEvent,
  Profile,
  ShopProduct,
} from "@/types/domain";

export const profiles: Profile[] = [
  {
    id: "ananya",
    name: "Ananya",
    age: 28,
    pronouns: "she/her",
    city: "Indiranagar, Bengaluru",
    distanceKm: 1.2,
    photo: "/images/profiles/ananya.webp",
    photos: ["/images/profiles/ananya.webp"],
    verified: true,
    online: true,
    compatibility: 94,
    occupation: "Product Designer",
    company: "Fintech studio",
    education: "NID Ahmedabad",
    bio: "Designing calm interfaces by day, hunting for the city’s best filter coffee by weekend.",
    prompt: {
      question: "The quickest way to my heart is…",
      answer: "A thoughtful playlist and punctual brunch plans.",
    },
    interests: ["Design", "Filter coffee", "Indie music", "Travel", "Dogs"],
    languages: ["English", "Kannada", "Hindi"],
    heightCm: 165,
    religion: "Hindu",
    relationshipGoal: "Long-term relationship",
    lifestyle: {
      drinking: "Socially",
      smoking: "Never",
      pets: "Dog person",
      workout: "Often",
    },
  },
  {
    id: "arjun",
    name: "Arjun",
    age: 31,
    pronouns: "he/him",
    city: "Bandra West, Mumbai",
    distanceKm: 2.4,
    photo: "/images/profiles/arjun.webp",
    photos: ["/images/profiles/arjun.webp"],
    verified: true,
    online: false,
    compatibility: 91,
    occupation: "Documentary Filmmaker",
    company: "Independent",
    education: "Whistling Woods",
    bio: "I collect small stories, big sunsets, and restaurant recommendations I fully intend to try.",
    prompt: {
      question: "Together, we could…",
      answer:
        "Take the last local to nowhere and find the best late-night chai.",
    },
    interests: ["Cinema", "Photography", "Street food", "Cricket", "Jazz"],
    languages: ["English", "Hindi", "Marathi"],
    heightCm: 178,
    religion: "Agnostic",
    relationshipGoal: "Life partner",
    lifestyle: {
      drinking: "Socially",
      smoking: "Never",
      pets: "Cat person",
      workout: "Sometimes",
    },
  },
  {
    id: "meera",
    name: "Meera",
    age: 26,
    pronouns: "she/her",
    city: "Hauz Khas, Delhi",
    distanceKm: 3.1,
    photo: "/images/profiles/meera.webp",
    photos: ["/images/profiles/meera.webp"],
    verified: true,
    online: true,
    compatibility: 89,
    occupation: "Arts Curator",
    company: "Independent gallery",
    education: "JNU",
    bio: "Art, old Delhi walks, and conversations that get unexpectedly specific.",
    prompt: {
      question: "A life goal of mine…",
      answer: "Build a public art archive anyone can wander through.",
    },
    interests: ["Art", "Museums", "Poetry", "Books", "Cooking"],
    languages: ["English", "Hindi", "Tamil"],
    heightCm: 162,
    religion: "Spiritual",
    relationshipGoal: "Dating",
    lifestyle: {
      drinking: "Rarely",
      smoking: "Never",
      pets: "Both",
      workout: "Sometimes",
    },
  },
  {
    id: "kabir",
    name: "Kabir",
    age: 29,
    pronouns: "he/him",
    city: "Jubilee Hills, Hyderabad",
    distanceKm: 4.8,
    photo: "/images/profiles/kabir.webp",
    photos: ["/images/profiles/kabir.webp"],
    verified: false,
    online: true,
    compatibility: 86,
    occupation: "Climate Researcher",
    company: "Urban futures lab",
    education: "IIT Madras",
    bio: "Usually on a bicycle, occasionally at a keyboard, always up for biryani.",
    prompt: {
      question: "My simple pleasures…",
      answer: "First rain, empty cycling lanes, and a perfectly timed joke.",
    },
    interests: ["Cycling", "Climate", "Biryani", "Coding", "Trekking"],
    languages: ["English", "Hindi", "Telugu"],
    heightCm: 181,
    religion: "Muslim",
    relationshipGoal: "Open to exploring",
    lifestyle: {
      drinking: "Never",
      smoking: "Never",
      pets: "Dog person",
      workout: "Daily",
    },
  },
];

export const conversations: Conversation[] = [
  {
    id: "chat-ananya",
    profile: profiles[0],
    lastMessage: "The Cubbon Park plan sounds perfect 🌿",
    time: "2m",
    unread: 2,
    typing: true,
  },
  {
    id: "chat-meera",
    profile: profiles[2],
    lastMessage: "I’ll send you the exhibit link!",
    time: "18m",
    unread: 0,
  },
  {
    id: "chat-arjun",
    profile: profiles[1],
    lastMessage: "That film was genuinely beautiful.",
    time: "Yesterday",
    unread: 0,
  },
];

export const chatMessages: ChatMessage[] = [
  {
    id: "m1",
    sender: "them",
    body: "Okay, important question: filter coffee or cold brew?",
    sentAt: "10:24",
  },
  {
    id: "m2",
    sender: "me",
    body: "Filter coffee when I need comfort. Cold brew when I’m pretending to be productive 😄",
    sentAt: "10:26",
    status: "seen",
  },
  {
    id: "m3",
    sender: "them",
    body: "Correct answer. There’s a tiny place near Cubbon Park I think you’d love.",
    sentAt: "10:28",
  },
  {
    id: "m4",
    sender: "me",
    body: "The Cubbon Park plan sounds perfect 🌿",
    sentAt: "10:31",
    status: "seen",
  },
];

export const communities: Community[] = [
  {
    id: "weekend-trekkers",
    name: "Weekend Trekkers",
    image: "/images/communities/weekend-trekkers.webp",
    category: "Travel",
    members: 12840,
    description: "Find a trail, a crew, and a reason to wake up early.",
    joined: true,
    privacy: "Public",
  },
  {
    id: "frame-by-frame",
    name: "Frame by Frame",
    image: "/images/communities/frame-by-frame.webp",
    category: "Movies",
    members: 8920,
    description: "Films, screenings, and politely intense debates.",
    joined: false,
    privacy: "Public",
  },
  {
    id: "build-in-public",
    name: "Build in Public",
    image: "/images/communities/build-in-public.webp",
    category: "Coding",
    members: 6540,
    description: "For people making thoughtful things on the internet.",
    joined: false,
    privacy: "Public",
  },
  {
    id: "pages-and-chai",
    name: "Pages & Chai",
    image: "/images/communities/pages-and-chai.webp",
    category: "Books",
    members: 4720,
    description: "Monthly reads, quiet meetups, warm cups.",
    joined: true,
    privacy: "Private",
  },
];

export const events: NearbyEvent[] = [
  {
    id: "slow-dating",
    title: "Slow Dating Social",
    date: "Sat, 7:00 PM",
    venue: "The Courtyard",
    distanceKm: 1.8,
    attendees: 48,
    category: "Dating",
    gradient: "from-primary to-sky-400",
  },
  {
    id: "coffee-club",
    title: "Sunday Coffee Club",
    date: "Sun, 11:00 AM",
    venue: "Bloom Coffee",
    distanceKm: 2.6,
    attendees: 31,
    category: "Coffee",
    gradient: "from-amber-500 to-orange-700",
  },
  {
    id: "board-games",
    title: "Board Games & Bites",
    date: "Sun, 5:30 PM",
    venue: "Dialogues Cafe",
    distanceKm: 4.1,
    attendees: 64,
    category: "Gaming",
    gradient: "from-secondary to-blue-500",
  },
];

export const gifts: Gift[] = [
  {
    id: "coffee",
    name: "Coffee date",
    emoji: "☕",
    description: "A warm cup at a partner cafe",
    value: "₹250",
    color: "bg-amber-50",
  },
  {
    id: "movie",
    name: "Movie night",
    emoji: "🎟️",
    description: "One cinema voucher",
    value: "₹500",
    color: "bg-sky-50",
  },
  {
    id: "flowers",
    name: "Fresh flowers",
    emoji: "💐",
    description: "Seasonal bouquet delivery",
    value: "₹699",
    color: "bg-blue-50",
  },
  {
    id: "chocolate",
    name: "Chocolate box",
    emoji: "🍫",
    description: "Artisan chocolate selection",
    value: "₹449",
    color: "bg-orange-50",
  },
];

export const shopProducts: ShopProduct[] = [
  {
    id: "blue-bloom-bouquet",
    name: "Blue Bloom Bouquet",
    description: "Fresh white and powder-blue flowers, wrapped by hand.",
    category: "Flowers",
    pricePaise: 149900,
    compareAtPricePaise: 179900,
    image: "/images/shop/blue-bloom-bouquet.webp",
    badge: "Bestseller",
    rating: 4.9,
    stock: 18,
  },
  {
    id: "coffee-date-kit",
    name: "Coffee Date Kit",
    description: "Artisan coffee, two ceramic cups, and cookies for two.",
    category: "Food",
    pricePaise: 129900,
    image: "/images/shop/coffee-date-kit.webp",
    badge: "Date night",
    rating: 4.8,
    stock: 24,
  },
  {
    id: "midnight-chocolate-box",
    name: "Midnight Chocolate Box",
    description:
      "A generous selection of handcrafted milk and dark chocolates.",
    category: "Food",
    pricePaise: 89900,
    compareAtPricePaise: 109900,
    image: "/images/shop/midnight-chocolate-box.webp",
    rating: 4.9,
    stock: 32,
  },
  {
    id: "together-journal",
    name: "Together Journal",
    description: "A linen-bound journal for memories, plans, and little notes.",
    category: "Keepsakes",
    pricePaise: 69900,
    image: "/images/shop/together-journal.webp",
    badge: "New",
    rating: 4.7,
    stock: 16,
  },
  {
    id: "celebration-cake",
    name: "Celebration Cake for Two",
    description: "A small vanilla cake with blue ombré buttercream.",
    category: "Food",
    pricePaise: 79900,
    image: "/images/shop/celebration-cake.webp",
    badge: "Same day",
    rating: 4.8,
    stock: 10,
  },
];
