-- The Atom production schema
-- Requires Supabase PostgreSQL 15+

create extension if not exists pgcrypto;
create extension if not exists postgis with schema extensions;

create type public.gender as enum ('woman', 'man', 'non_binary', 'self_described');
create type public.relationship_goal as enum (
  'long_term',
  'life_partner',
  'dating',
  'exploring'
);
create type public.like_kind as enum ('like', 'super_like');
create type public.message_kind as enum ('text', 'image', 'gif', 'voice', 'gift', 'system');
create type public.group_privacy as enum ('public', 'private');
create type public.member_role as enum ('member', 'moderator', 'owner');
create type public.verification_status as enum ('pending', 'approved', 'rejected', 'expired');
create type public.report_status as enum ('open', 'reviewing', 'resolved', 'dismissed');
create type public.gift_status as enum ('pending', 'accepted', 'rejected', 'claimed', 'expired');
create type public.profile_action_kind as enum ('pass', 'hide', 'bookmark');

create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  phone text,
  email text,
  locale text not null default 'en-IN',
  timezone text not null default 'Asia/Kolkata',
  onboarding_complete boolean not null default false,
  is_active boolean not null default true,
  last_active_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.profiles (
  user_id uuid primary key references public.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 2 and 40),
  birth_date date not null check (birth_date <= current_date - interval '18 years'),
  gender public.gender not null,
  pronouns text,
  bio text check (char_length(bio) <= 500),
  occupation text,
  company text,
  education text,
  height_cm smallint check (height_cm between 120 and 230),
  religion text,
  languages text[] not null default '{}',
  relationship_goal public.relationship_goal,
  drinking text,
  smoking text,
  pets text,
  workout text,
  travel text,
  instagram_handle text,
  spotify_connected boolean not null default false,
  prompt_answers jsonb not null default '[]'::jsonb,
  is_verified boolean not null default false,
  is_incognito boolean not null default false,
  is_discoverable boolean not null default true,
  profile_score smallint not null default 0 check (profile_score between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.photos (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  storage_path text not null,
  sort_order smallint not null default 0,
  is_primary boolean not null default false,
  moderation_status text not null default 'pending',
  width integer,
  height integer,
  blurhash text,
  created_at timestamptz not null default now(),
  unique (user_id, storage_path)
);

create unique index one_primary_photo_per_user
  on public.photos(user_id) where is_primary;

create table public.interests (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text not null,
  icon text,
  is_active boolean not null default true
);

create table public.profile_interests (
  user_id uuid not null references public.users(id) on delete cascade,
  interest_id bigint not null references public.interests(id) on delete cascade,
  affinity smallint not null default 1 check (affinity between 1 and 5),
  primary key (user_id, interest_id)
);

create table public.preferences (
  user_id uuid primary key references public.users(id) on delete cascade,
  interested_in public.gender[] not null default '{}',
  min_age smallint not null default 18 check (min_age >= 18),
  max_age smallint not null default 99 check (max_age >= min_age),
  max_distance_km numeric(6,2) not null default 50 check (max_distance_km > 0),
  min_height_cm smallint,
  max_height_cm smallint,
  religions text[] not null default '{}',
  languages text[] not null default '{}',
  education_levels text[] not null default '{}',
  relationship_goals public.relationship_goal[] not null default '{}',
  verified_only boolean not null default false,
  recently_active_only boolean not null default false,
  updated_at timestamptz not null default now()
);

create table public.locations (
  user_id uuid primary key references public.users(id) on delete cascade,
  city text,
  locality text,
  country_code char(2) not null default 'IN',
  point extensions.geography(point, 4326),
  geohash text,
  sharing_precision text not null default 'approximate',
  updated_at timestamptz not null default now()
);

create index locations_point_gix on public.locations using gist(point);

create table public.likes (
  id uuid primary key default gen_random_uuid(),
  actor_user_id uuid not null default auth.uid() references public.users(id) on delete cascade,
  target_user_id uuid not null references public.users(id) on delete cascade,
  kind public.like_kind not null default 'like',
  created_at timestamptz not null default now(),
  unique(actor_user_id, target_user_id),
  check (actor_user_id <> target_user_id)
);

create table public.profile_actions (
  actor_user_id uuid not null default auth.uid() references public.users(id) on delete cascade,
  target_user_id uuid not null references public.users(id) on delete cascade,
  action public.profile_action_kind not null,
  created_at timestamptz not null default now(),
  primary key(actor_user_id, target_user_id, action),
  check (actor_user_id <> target_user_id)
);

create table public.matches (
  id uuid primary key default gen_random_uuid(),
  user_a_id uuid not null references public.users(id) on delete cascade,
  user_b_id uuid not null references public.users(id) on delete cascade,
  matched_at timestamptz not null default now(),
  unmatched_at timestamptz,
  initiated_by uuid references public.users(id),
  unique(user_a_id, user_b_id),
  check (user_a_id < user_b_id)
);

create table public.chats (
  id uuid primary key default gen_random_uuid(),
  match_id uuid unique references public.matches(id) on delete cascade,
  group_id uuid,
  is_archived boolean not null default false,
  last_message_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.chat_members (
  chat_id uuid not null references public.chats(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_read_at timestamptz,
  is_muted boolean not null default false,
  is_pinned boolean not null default false,
  primary key(chat_id, user_id)
);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  chat_id uuid not null references public.chats(id) on delete cascade,
  sender_user_id uuid not null default auth.uid() references public.users(id) on delete cascade,
  message_type public.message_kind not null default 'text',
  body text check (char_length(body) <= 5000),
  media_path text,
  reply_to_id uuid references public.messages(id) on delete set null,
  forwarded_from_id uuid references public.messages(id) on delete set null,
  is_pinned boolean not null default false,
  edited_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz not null default now()
);

create index messages_chat_created_idx on public.messages(chat_id, created_at desc);

create table public.groups (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null check (char_length(name) between 2 and 80),
  description text check (char_length(description) <= 1000),
  category text not null,
  cover_path text,
  privacy public.group_privacy not null default 'public',
  created_by uuid not null default auth.uid() references public.users(id),
  member_count integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.chats
  add constraint chats_group_id_fkey foreign key (group_id)
  references public.groups(id) on delete cascade;

create table public.group_members (
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  role public.member_role not null default 'member',
  status text not null default 'active',
  joined_at timestamptz not null default now(),
  primary key(group_id, user_id)
);

create table public.group_posts (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups(id) on delete cascade,
  author_user_id uuid not null default auth.uid() references public.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 5000),
  media_paths text[] not null default '{}',
  poll jsonb,
  is_pinned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.events (
  id uuid primary key default gen_random_uuid(),
  group_id uuid references public.groups(id) on delete set null,
  created_by uuid not null default auth.uid() references public.users(id),
  title text not null check (char_length(title) between 3 and 120),
  description text,
  category text not null,
  venue_name text,
  location extensions.geography(point, 4326),
  address text,
  starts_at timestamptz not null,
  ends_at timestamptz,
  capacity integer check (capacity > 0),
  visibility text not null default 'public',
  created_at timestamptz not null default now()
);

create index events_location_gix on public.events using gist(location);
create index events_starts_idx on public.events(starts_at);

create table public.event_attendees (
  event_id uuid not null references public.events(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  status text not null default 'going',
  joined_at timestamptz not null default now(),
  primary key(event_id, user_id)
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  actor_user_id uuid references public.users(id) on delete set null,
  type text not null,
  title text not null,
  body text,
  data jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index notifications_user_created_idx
  on public.notifications(user_id, created_at desc);

create table public.verifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  type text not null,
  status public.verification_status not null default 'pending',
  provider_reference text,
  evidence_path text,
  reviewed_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_user_id uuid not null default auth.uid() references public.users(id) on delete cascade,
  reported_user_id uuid references public.users(id) on delete set null,
  message_id uuid references public.messages(id) on delete set null,
  group_id uuid references public.groups(id) on delete set null,
  reason text not null,
  details text,
  evidence_paths text[] not null default '{}',
  status public.report_status not null default 'open',
  resolution_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.blocks (
  blocker_user_id uuid not null default auth.uid() references public.users(id) on delete cascade,
  blocked_user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(blocker_user_id, blocked_user_id),
  check (blocker_user_id <> blocked_user_id)
);

create table public.mutes (
  muting_user_id uuid not null default auth.uid() references public.users(id) on delete cascade,
  muted_user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(muting_user_id, muted_user_id),
  check (muting_user_id <> muted_user_id)
);

create table public.gifts (
  id uuid primary key default gen_random_uuid(),
  sender_user_id uuid not null default auth.uid() references public.users(id),
  receiver_user_id uuid not null references public.users(id),
  gift_type text not null,
  provider text,
  provider_reference text,
  amount_minor integer not null check (amount_minor >= 0),
  currency char(3) not null default 'INR',
  message text check (char_length(message) <= 160),
  status public.gift_status not null default 'pending',
  expires_at timestamptz not null default now() + interval '30 days',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (sender_user_id <> receiver_user_id)
);

create table public.gift_claims (
  id uuid primary key default gen_random_uuid(),
  gift_id uuid not null unique references public.gifts(id) on delete cascade,
  receiver_user_id uuid not null references public.users(id),
  claim_reference text,
  claimed_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.ai_suggestions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  capability text not null,
  provider text not null,
  model text not null,
  input_hash text not null,
  suggestion jsonb not null,
  safety_metadata jsonb not null default '{}'::jsonb,
  accepted_at timestamptz,
  dismissed_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create index ai_suggestions_user_capability_idx
  on public.ai_suggestions(user_id, capability, created_at desc);

-- Shared timestamp trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger users_set_updated_at before update on public.users
  for each row execute function public.set_updated_at();
create trigger profiles_set_updated_at before update on public.profiles
  for each row execute function public.set_updated_at();
create trigger groups_set_updated_at before update on public.groups
  for each row execute function public.set_updated_at();
create trigger group_posts_set_updated_at before update on public.group_posts
  for each row execute function public.set_updated_at();
create trigger reports_set_updated_at before update on public.reports
  for each row execute function public.set_updated_at();
create trigger gifts_set_updated_at before update on public.gifts
  for each row execute function public.set_updated_at();

-- Mirror auth users into application users.
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.users(id, phone, email)
  values(new.id, new.phone, new.email)
  on conflict(id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_auth_user();

-- Match creation is transactional and deterministic.
create or replace function public.create_match_after_like()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
declare
  new_match_id uuid;
  new_chat_id uuid;
  left_user uuid;
  right_user uuid;
begin
  if exists (
    select 1 from public.likes
    where actor_user_id = new.target_user_id
      and target_user_id = new.actor_user_id
  ) then
    left_user := least(new.actor_user_id, new.target_user_id);
    right_user := greatest(new.actor_user_id, new.target_user_id);

    insert into public.matches(user_a_id, user_b_id, initiated_by)
    values(left_user, right_user, new.actor_user_id)
    on conflict(user_a_id, user_b_id)
    do update set unmatched_at = null
    returning id into new_match_id;

    insert into public.chats(match_id)
    values(new_match_id)
    on conflict(match_id) do update set is_archived = false
    returning id into new_chat_id;

    insert into public.chat_members(chat_id, user_id)
    values(new_chat_id, left_user), (new_chat_id, right_user)
    on conflict do nothing;

    insert into public.notifications(user_id, actor_user_id, type, title, data)
    values
      (left_user, right_user, 'match', 'It''s a match!', jsonb_build_object('match_id', new_match_id)),
      (right_user, left_user, 'match', 'It''s a match!', jsonb_build_object('match_id', new_match_id));
  end if;
  return new;
end;
$$;

create trigger on_like_create_match
  after insert or update on public.likes
  for each row execute function public.create_match_after_like();

create or replace function public.touch_chat_after_message()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  update public.chats set last_message_at = new.created_at where id = new.chat_id;
  return new;
end;
$$;

create trigger on_message_touch_chat
  after insert on public.messages
  for each row execute function public.touch_chat_after_message();

-- Discovery RPC: exact coordinates remain private.
create or replace function public.get_discovery_profiles(
  max_distance_km numeric default 50,
  min_age integer default 18,
  max_age integer default 99,
  verified_only boolean default false
)
returns table (
  user_id uuid,
  display_name text,
  age integer,
  bio text,
  occupation text,
  city text,
  distance_km numeric,
  is_verified boolean,
  profile_score integer
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    p.user_id,
    p.display_name,
    extract(year from age(p.birth_date))::integer as age,
    p.bio,
    p.occupation,
    l.city,
    round(
      (
        extensions.st_distance(
          l.point,
          viewer.point
        ) / 1000
      )::numeric,
      1
    ) as distance_km,
    p.is_verified,
    p.profile_score
  from public.profiles p
  join public.users u on u.id = p.user_id
  left join public.locations l on l.user_id = p.user_id
  left join public.locations viewer on viewer.user_id = auth.uid()
  where p.user_id <> auth.uid()
    and p.is_discoverable
    and not p.is_incognito
    and u.is_active
    and extract(year from age(p.birth_date)) between min_age and max_age
    and (not verified_only or p.is_verified)
    and (
      viewer.point is null
      or l.point is null
      or extensions.st_dwithin(l.point, viewer.point, max_distance_km * 1000)
    )
    and not exists (
      select 1 from public.blocks b
      where (b.blocker_user_id = auth.uid() and b.blocked_user_id = p.user_id)
         or (b.blocker_user_id = p.user_id and b.blocked_user_id = auth.uid())
    )
    and not exists (
      select 1 from public.profile_actions a
      where a.actor_user_id = auth.uid()
        and a.target_user_id = p.user_id
        and a.action in ('pass', 'hide')
    )
  order by
    case when viewer.point is null or l.point is null then 1 else 0 end,
    distance_km asc nulls last,
    p.profile_score desc;
$$;

grant execute on function public.get_discovery_profiles(numeric, integer, integer, boolean)
to authenticated;

-- RLS
alter table public.users enable row level security;
alter table public.profiles enable row level security;
alter table public.photos enable row level security;
alter table public.interests enable row level security;
alter table public.profile_interests enable row level security;
alter table public.preferences enable row level security;
alter table public.locations enable row level security;
alter table public.likes enable row level security;
alter table public.profile_actions enable row level security;
alter table public.matches enable row level security;
alter table public.chats enable row level security;
alter table public.chat_members enable row level security;
alter table public.messages enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.group_posts enable row level security;
alter table public.events enable row level security;
alter table public.event_attendees enable row level security;
alter table public.notifications enable row level security;
alter table public.verifications enable row level security;
alter table public.reports enable row level security;
alter table public.blocks enable row level security;
alter table public.mutes enable row level security;
alter table public.gifts enable row level security;
alter table public.gift_claims enable row level security;
alter table public.ai_suggestions enable row level security;

create policy "users read self" on public.users for select
  using (id = auth.uid());
create policy "users update self" on public.users for update
  using (id = auth.uid()) with check (id = auth.uid());

create policy "profiles discoverable or self" on public.profiles for select
  using (
    user_id = auth.uid()
    or (
      is_discoverable
      and not exists (
        select 1 from public.blocks b
        where (b.blocker_user_id = auth.uid() and b.blocked_user_id = user_id)
           or (b.blocker_user_id = user_id and b.blocked_user_id = auth.uid())
      )
    )
  );
create policy "profiles insert self" on public.profiles for insert
  with check (user_id = auth.uid());
create policy "profiles update self" on public.profiles for update
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "photos readable for visible profiles" on public.photos for select
  using (
    user_id = auth.uid()
    or exists (
      select 1 from public.profiles p
      where p.user_id = photos.user_id and p.is_discoverable
    )
  );
create policy "photos manage self" on public.photos for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "interests readable" on public.interests for select to authenticated
  using (is_active);
create policy "profile interests readable" on public.profile_interests for select
  using (true);
create policy "profile interests manage self" on public.profile_interests for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "preferences self" on public.preferences for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "locations self only" on public.locations for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "likes created and read by actor" on public.likes for all
  using (actor_user_id = auth.uid()) with check (actor_user_id = auth.uid());
create policy "profile actions self" on public.profile_actions for all
  using (actor_user_id = auth.uid()) with check (actor_user_id = auth.uid());
create policy "match members read" on public.matches for select
  using (auth.uid() in (user_a_id, user_b_id));
create policy "match members update" on public.matches for update
  using (auth.uid() in (user_a_id, user_b_id));

create policy "chat members read chat" on public.chats for select
  using (
    exists (
      select 1 from public.chat_members cm
      where cm.chat_id = chats.id and cm.user_id = auth.uid()
    )
  );
create policy "chat membership visible to members" on public.chat_members for select
  using (
    exists (
      select 1 from public.chat_members mine
      where mine.chat_id = chat_members.chat_id and mine.user_id = auth.uid()
    )
  );
create policy "chat members update self" on public.chat_members for update
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "messages visible to chat members" on public.messages for select
  using (
    exists (
      select 1 from public.chat_members cm
      where cm.chat_id = messages.chat_id and cm.user_id = auth.uid()
    )
  );
create policy "messages inserted by chat members" on public.messages for insert
  with check (
    sender_user_id = auth.uid()
    and exists (
      select 1 from public.chat_members cm
      where cm.chat_id = messages.chat_id and cm.user_id = auth.uid()
    )
  );
create policy "messages updated by sender" on public.messages for update
  using (sender_user_id = auth.uid()) with check (sender_user_id = auth.uid());

create policy "public groups or memberships readable" on public.groups for select
  using (
    privacy = 'public'
    or exists (
      select 1 from public.group_members gm
      where gm.group_id = groups.id and gm.user_id = auth.uid()
    )
  );
create policy "authenticated create groups" on public.groups for insert
  with check (created_by = auth.uid());
create policy "owners update groups" on public.groups for update
  using (
    exists (
      select 1 from public.group_members gm
      where gm.group_id = groups.id and gm.user_id = auth.uid()
        and gm.role in ('owner', 'moderator')
    )
  );
create policy "group membership readable" on public.group_members for select
  using (
    user_id = auth.uid()
    or exists (
      select 1 from public.groups g
      where g.id = group_members.group_id and g.privacy = 'public'
    )
  );
create policy "users join public groups" on public.group_members for insert
  with check (
    user_id = auth.uid()
    and exists (
      select 1 from public.groups g
      where g.id = group_members.group_id and g.privacy = 'public'
    )
  );
create policy "members leave groups" on public.group_members for delete
  using (user_id = auth.uid());
create policy "group posts visible to members or public" on public.group_posts for select
  using (
    exists (
      select 1 from public.groups g
      where g.id = group_posts.group_id and g.privacy = 'public'
    )
    or exists (
      select 1 from public.group_members gm
      where gm.group_id = group_posts.group_id and gm.user_id = auth.uid()
    )
  );
create policy "members create posts" on public.group_posts for insert
  with check (
    author_user_id = auth.uid()
    and exists (
      select 1 from public.group_members gm
      where gm.group_id = group_posts.group_id and gm.user_id = auth.uid()
    )
  );
create policy "authors update posts" on public.group_posts for update
  using (author_user_id = auth.uid()) with check (author_user_id = auth.uid());

create policy "public events readable" on public.events for select
  using (visibility = 'public' or created_by = auth.uid());
create policy "authenticated create events" on public.events for insert
  with check (created_by = auth.uid());
create policy "creators update events" on public.events for update
  using (created_by = auth.uid()) with check (created_by = auth.uid());
create policy "event attendance readable" on public.event_attendees for select
  using (true);
create policy "event attendance self" on public.event_attendees for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "notifications self" on public.notifications for select
  using (user_id = auth.uid());
create policy "notifications update self" on public.notifications for update
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "verifications self" on public.verifications for select
  using (user_id = auth.uid());
create policy "verifications create self" on public.verifications for insert
  with check (user_id = auth.uid());
create policy "reports self read" on public.reports for select
  using (reporter_user_id = auth.uid());
create policy "reports self create" on public.reports for insert
  with check (reporter_user_id = auth.uid());
create policy "blocks self" on public.blocks for all
  using (blocker_user_id = auth.uid()) with check (blocker_user_id = auth.uid());
create policy "mutes self" on public.mutes for all
  using (muting_user_id = auth.uid()) with check (muting_user_id = auth.uid());

create policy "gift participants read" on public.gifts for select
  using (auth.uid() in (sender_user_id, receiver_user_id));
create policy "send gifts as self" on public.gifts for insert
  with check (sender_user_id = auth.uid());
create policy "gift receiver updates" on public.gifts for update
  using (receiver_user_id = auth.uid());
create policy "gift claims receiver" on public.gift_claims for select
  using (receiver_user_id = auth.uid());
create policy "gift claims create receiver" on public.gift_claims for insert
  with check (receiver_user_id = auth.uid());
create policy "ai suggestions self" on public.ai_suggestions for select
  using (user_id = auth.uid());
create policy "ai suggestions update self" on public.ai_suggestions for update
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Storage
insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values
  ('profile-photos', 'profile-photos', true, 15728640, array['image/jpeg', 'image/png', 'image/webp']),
  ('chat-media', 'chat-media', false, 26214400, array['image/jpeg', 'image/png', 'image/webp', 'audio/mpeg', 'audio/mp4']),
  ('verification', 'verification', false, 26214400, array['image/jpeg', 'image/png', 'video/mp4'])
on conflict(id) do nothing;

create policy "public profile photos" on storage.objects for select
  using (bucket_id = 'profile-photos');
create policy "users upload profile photos to own folder" on storage.objects for insert
  with check (
    bucket_id = 'profile-photos'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
create policy "users manage own profile photos" on storage.objects for update
  using (
    bucket_id = 'profile-photos'
    and owner_id = auth.uid()::text
  );
create policy "users delete own profile photos" on storage.objects for delete
  using (
    bucket_id = 'profile-photos'
    and owner_id = auth.uid()::text
  );

create policy "chat members read chat media" on storage.objects for select
  using (
    bucket_id = 'chat-media'
    and exists (
      select 1 from public.chat_members cm
      where cm.chat_id::text = (storage.foldername(name))[1]
        and cm.user_id = auth.uid()
    )
  );
create policy "chat members upload chat media" on storage.objects for insert
  with check (
    bucket_id = 'chat-media'
    and exists (
      select 1 from public.chat_members cm
      where cm.chat_id::text = (storage.foldername(name))[1]
        and cm.user_id = auth.uid()
    )
  );
create policy "verification media self" on storage.objects for all
  using (
    bucket_id = 'verification'
    and (storage.foldername(name))[1] = auth.uid()::text
  )
  with check (
    bucket_id = 'verification'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- Realtime tables
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.notifications;
alter publication supabase_realtime add table public.matches;
alter publication supabase_realtime add table public.chat_members;

-- Seed interests
insert into public.interests(name, category, icon) values
  ('Travel', 'Lifestyle', 'plane'),
  ('Music', 'Culture', 'music'),
  ('Movies', 'Culture', 'film'),
  ('Books', 'Culture', 'book'),
  ('Fitness', 'Lifestyle', 'dumbbell'),
  ('Cooking', 'Lifestyle', 'chef-hat'),
  ('Photography', 'Creative', 'camera'),
  ('Gaming', 'Entertainment', 'gamepad'),
  ('Coding', 'Technology', 'code'),
  ('Pets', 'Lifestyle', 'paw-print'),
  ('Cricket', 'Sports', 'trophy'),
  ('Art', 'Creative', 'palette')
on conflict(name) do nothing;
